const labels=['מסמכי הוצאות','דוח מכירות','תדפיס בנק'];
const descriptions=['חשבוניות וקבלות על הוצאות העסק לחודש אוגוסט','דוח המכירות החודשי ממערכת הקופה או הנהלת החשבונות','תדפיס תנועות חשבון הבנק לחודש אוגוסט'];
const initial=()=>[
 {id:'dana',name:'דנה כהן',business:'הקונדיטוריה של דנה',initial:'ד',color:'teal',owner:'מיכל',docs:[{status:'received',file:'הוצאות-אוגוסט.pdf'},{status:'received',file:'מכירות-אוגוסט.pdf'},{status:'missing'}],events:[{time:'09:12',text:'דנה השלימה את העלאת מסמכי ההוצאות ודוח המכירות.'}]},
 {id:'amir',name:'אמיר רוזן',business:'סטודיו רוזן לעיצוב',initial:'א',color:'gold',owner:'יעל',docs:[{status:'received',file:'הוצאות-סטודיו.pdf'},{status:'received',file:'דוח-מכירות.pdf'},{status:'received',file:'בנק-אוגוסט.pdf'}],events:[{time:'08:45',text:'כל הפריטים התקבלו. החומר ממתין לבדיקת הצוות.'}]},
 {id:'ron',name:'רון לוי',business:'רון שירותי מחשוב',initial:'ר',color:'blue',owner:'מיכל',docs:[{status:'approved',file:'הוצאות-אוגוסט.pdf'},{status:'approved',file:'מכירות-אוגוסט.pdf'},{status:'approved',file:'בנק-אוגוסט.pdf'}],events:[{time:'08:30',text:'החומר אושר. נוצרה משימת טיפול למיכל.'}],task:true}
];
let clients=initial(),selected='dana',view='office',rejectIndex=null,reminderClient=null;
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>clients.find(c=>c.id===selected);
const received=c=>c.docs.filter(d=>['received','approved'].includes(d.status)).length;
const ready=c=>c.docs.every(d=>d.status==='approved');
const missing=c=>c.docs.map((d,i)=>['missing','rejected'].includes(d.status)?i:null).filter(i=>i!==null);
function state(c){if(ready(c))return ['מוכן לטיפול','green'];if(c.docs.some(d=>d.status==='rejected'))return ['נדרשת השלמה','red'];if(received(c)===3)return ['ממתין לבדיקה','blue'];return ['חומר חלקי','amber'];}
function badge(c){const [t,k]=state(c);return `<span class="badge ${k}">${t}</span>`;}
function docBadge(d){const dict={missing:['טרם התקבל','amber'],received:['התקבל · לבדיקה','blue'],approved:['נבדק ואושר','green'],rejected:['נדרשת השלמה','red']};const [t,k]=dict[d.status];return `<span class="badge ${k}">${t}</span>`;}
function log(c,text){c.events.unshift({time:new Date().toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}),text});}
let toastTimer;function toast(text){const e=document.getElementById('toast');e.textContent=text;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3600);}
function setView(v){view=v;rejectIndex=null;render();window.scrollTo({top:0,behavior:'smooth'});}
function selectClient(id){if(!clients.some(c=>c.id===id))throw Error('לקוח לא קיים');selected=id;rejectIndex=null;render();}
function progress(c){return `<div class="progress-label"><span>${ready(c)?'כל החומר נבדק ואושר':'התקדמות איסוף החומר'}</span><span>${received(c)} מתוך 3 פריטים התקבלו</span></div><div class="progress" role="progressbar" aria-label="התקדמות איסוף החומר" aria-valuenow="${received(c)}" aria-valuemin="0" aria-valuemax="3"><div style="width:${received(c)/3*100}%"></div></div>`;}
function render(){document.getElementById('office-tab').classList.toggle('active',view==='office');document.getElementById('client-tab').classList.toggle('active',view==='client');document.getElementById('office-tab').setAttribute('aria-pressed',view==='office');document.getElementById('client-tab').setAttribute('aria-pressed',view==='client');app.innerHTML=view==='office'?office():clientPage();bind();}
function office(){const c=current();return `<div class="page-heading"><div><span class="eyebrow">תמונת המצב של המשרד</span><h1>פחות לרדוף. יותר להתקדם.</h1><p>כל החומרים, ההשלמות והלקוחות — במקום אחד.</p></div><div class="period">אוגוסט 2026<small>תקופת ההדגמה</small></div></div>
<section class="stats" aria-label="סיכום תיקים"><div class="stat"><i>▤</i><strong>3</strong><span>לקוחות במעקב</span></div><div class="stat"><i>◷</i><strong>${clients.filter(c=>missing(c).length).length}</strong><span>ממתינים להשלמות</span></div><div class="stat"><i>≡</i><strong>${clients.filter(c=>received(c)===3&&!ready(c)).length}</strong><span>ממתינים לבדיקת הצוות</span></div><div class="stat"><i>✓</i><strong>${clients.filter(ready).length}</strong><span>תיקים מוכנים לטיפול</span></div></section>
<div class="workspace"><aside><section class="panel"><div class="panel-head"><h2>הלקוחות שלי</h2><span class="count">3 לקוחות</span></div><div class="clients">${clients.map(x=>`<button class="client-row ${x.id===selected?'selected':''}" data-client="${x.id}" aria-pressed="${x.id===selected}"><div class="client-top"><span class="avatar ${x.color}">${x.initial}</span><span><strong>${x.business}</strong><small>${x.name}</small></span><span class="chevron">‹</span></div><div class="row-bottom">${badge(x)}<span class="mini-progress">${[0,1,2].map(i=>`<i class="${i<received(x)?'filled':''}"></i>`).join('')} ${received(x)}/3</span></div></button>`).join('')}</div></section><div class="hint"><strong>כך תדגימו את התהליך</strong>עברו לתצוגת הלקוח של דנה, הוסיפו תדפיס בנק לדוגמה וחזרו לכאן כדי לבדוק ולאשר את החומר.</div></aside>
<section><div class="panel"><div class="detail-top"><div class="detail-title"><div><h2>${c.business}</h2><small>${c.name} · אחראית: ${c.owner} · אוגוסט 2026</small></div>${badge(c)}</div>${progress(c)}${ready(c)?`<div class="ready-note">✓ החומר מוכן. משימת טיפול הוקצתה ל${c.owner}.</div>`:''}</div><div class="docs">${c.docs.map((d,i)=>`<div class="doc"><span class="doc-icon">▤</span><div class="doc-info"><strong>${labels[i]}</strong><small>${d.file?esc(d.file):'ממתינים להעלאה מהלקוח'}${d.note?' · '+esc(d.note):''}</small></div><div class="doc-actions">${docBadge(d)}${d.status==='received'?`<button class="approve" data-approve="${i}" aria-label="אישור ${labels[i]}">אישור ✓</button><button data-reject="${i}" aria-label="בקשת תיקון ${labels[i]}">תיקון</button>`:''}</div></div>`).join('')}</div>
${rejectIndex!==null?`<form class="reject-form" id="reject-form"><label for="reason">מה צריך להשלים ב${labels[rejectIndex]}?</label><input id="reason" required maxlength="160" placeholder="לדוגמה: התדפיס הוא של יולי, נדרש תדפיס אוגוסט"><div class="actions"><button class="primary" type="submit">שמירת בקשת השלמה</button><button type="button" id="cancel-reject">ביטול</button></div></form>`:''}
<div class="detail-footer"><button class="primary" id="remind" ${missing(c).length?'':'disabled'}>הכנת תזכורת להשלמות</button><button class="text-button" id="view-client">פתיחת תצוגת הלקוח ↗</button></div></div><section class="panel activity"><h3>מה קרה בתיק</h3>${c.events.map(e=>`<div class="event"><span class="event-icon">✓</span><span>${esc(e.text)}</span><time>${e.time}</time></div>`).join('')}</section></section></div><div class="footer-note">דמו אינטראקטיבי · השינויים נשמרים רק במהלך הביקור הנוכחי · אין חיבור למערכות המשרד</div>`;}
function clientPage(){const c=current();return `<div class="client-page"><div class="client-switch"><span class="muted">תצוגת לקוח לדוגמה</span><select id="client-select" aria-label="בחירת לקוח להדגמה">${clients.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${x.name} · ${x.business}</option>`).join('')}</select></div><section class="welcome"><span class="eyebrow">נועה ושות׳ · איסוף חומרים לאוגוסט 2026</span><h1>שלום ${c.name.split(' ')[0]}, ${ready(c)?'החומר שלך מוכן ✓':'בואו נסגור את החודש.'}</h1><p>${ready(c)?'צוות המשרד בדק ואישר את החומרים ששלחת. הכול מוכן להמשך טיפול.':received(c)===3?'תודה! כל הפריטים התקבלו וממתינים לבדיקת הצוות. נעדכן אם נדרשת השלמה.':'כאן אפשר לראות מה כבר התקבל ולהשלים את החומר החסר. אין צורך לשלוח שוב פריטים שכבר התקבלו.'}</p>${progress(c)}</section><section class="panel">${c.docs.map((d,i)=>`<div class="client-doc"><div class="client-doc-head"><div><h3>${labels[i]}</h3><small>${descriptions[i]}</small></div>${docBadge(d)}</div>${d.status==='rejected'?`<div class="review-note">הערת המשרד: ${esc(d.note)}</div>`:''}${['missing','rejected'].includes(d.status)?`<div class="upload-zone"><p>השלמת הפריט באמצעות מסמך פיקטיבי מוכן.<br><small>אין צורך לבחור קובץ מהמחשב.</small></p><button class="primary" data-upload="${i}">הוספת מסמך לדוגמה ＋</button></div>`:`<small style="margin-top:12px">▤ ${esc(d.file)} · ${d.status==='approved'?'אושר על ידי צוות המשרד':'העלאת הפריט הושלמה'}</small>`}</div>`).join('')}</section><p class="client-bottom">המסמכים והרשימה בדמו נועדו להמחשה בלבד.<br>במערכת המחוברת, המשרד יגדיר את הדרישות לכל לקוח.</p></div>`;}
function upload(index){const c=current();if(!Number.isInteger(index)||!c.docs[index]||!['missing','rejected'].includes(c.docs[index].status))throw Error('הפריט אינו ממתין להשלמה');c.docs[index]={status:'received',file:labels[index].replaceAll(' ','-')+'-אוגוסט-דוגמה.pdf'};log(c,`התקבל בהדמיה: ${labels[index]}. ${received(c)===3?'כל החומר התקבל; תזכורות האיסוף נעצרו.':'רשימת החוסרים עודכנה.'}`);render();toast('המסמך לדוגמה נוסף. מצב התיק עודכן גם במשרד.');return {client:c.id,received:received(c),status:state(c)[0]};}
function approve(index){const c=current();if(c.docs[index]?.status!=='received')throw Error('אפשר לאשר רק פריט שהתקבל');c.docs[index].status='approved';log(c,`אושר על ידי ${c.owner}: ${labels[index]}.`);if(ready(c)){c.task=true;log(c,`התיק מוכן לטיפול. נוצרה משימה ל${c.owner}.`);toast('כל החומר אושר! התיק מוכן לטיפול.');}else toast('הפריט אושר.');render();}
function bind(){document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>selectClient(b.dataset.client));document.querySelectorAll('[data-upload]').forEach(b=>b.onclick=()=>upload(Number(b.dataset.upload)));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(Number(b.dataset.approve)));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>{rejectIndex=Number(b.dataset.reject);render();document.getElementById('reason').focus();});const select=document.getElementById('client-select');if(select)select.onchange=()=>selectClient(select.value);const vc=document.getElementById('view-client');if(vc)vc.onclick=()=>setView('client');const cancel=document.getElementById('cancel-reject');if(cancel)cancel.onclick=()=>{rejectIndex=null;render();};const form=document.getElementById('reject-form');if(form)form.onsubmit=e=>{e.preventDefault();const note=document.getElementById('reason').value.trim();if(!note){toast('יש להזין את ההשלמה הנדרשת');return;}const c=current();c.docs[rejectIndex].status='rejected';c.docs[rejectIndex].note=note;log(c,`נדרשת השלמה: ${labels[rejectIndex]} — ${note}`);rejectIndex=null;render();toast('בקשת ההשלמה מופיעה כעת בתצוגת הלקוח.');};const remind=document.getElementById('remind');if(remind)remind.onclick=()=>{const c=current();reminderClient=c.id;document.getElementById('message').textContent=`אל: ${c.name} (${c.business})\nנושא: השלמת חומרים לאוגוסט 2026\n\nשלום ${c.name.split(' ')[0]},\n${received(c)?'תודה על החומרים שכבר שלחת. ':''}להשלמת החומר לחודש אוגוסט נדרשים כעת:\n${missing(c).map(i=>'• '+labels[i]+(c.docs[i].note?' — '+c.docs[i].note:'')).join('\n')}\n\nאפשר להשלים דרך טופס החומרים האישי.\nתודה, צוות נועה ושות׳`;document.getElementById('reminder').showModal();};}
document.getElementById('office-tab').onclick=()=>setView('office');document.getElementById('client-tab').onclick=()=>setView('client');document.getElementById('reset').onclick=()=>document.getElementById('reset-dialog').showModal();document.getElementById('cancel-reset').onclick=()=>document.getElementById('reset-dialog').close();document.getElementById('confirm-reset').onclick=()=>{clients=initial();selected='dana';view='office';rejectIndex=null;document.getElementById('reset-dialog').close();render();toast('הדמו אופס. אפשר להתחיל מחדש.');};document.getElementById('send-reminder').onclick=()=>{const c=clients.find(c=>c.id===reminderClient);if(c&&missing(c).length)log(c,`הדמיית תזכורת: בקשה להשלמת ${missing(c).map(i=>labels[i]).join(', ')}. לא נשלחה הודעה בפועל.`);document.getElementById('reminder').close();render();toast('התזכורת נוספה ליומן ההדגמה. לא נשלחה הודעה.');};
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_demo_cases',description:'Read the fictional accounting cases and document statuses in this demo.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>clients.map(c=>({id:c.id,name:c.name,status:state(c)[0],documents:c.docs.map((d,i)=>({name:labels[i],status:d.status}))}))})).catch(()=>{});}catch{}}

