import {$,esc,status,badge,date,toast,api,progress} from './common.mjs';
const token=location.hash.slice(1),app=$('#app');
const call=(path,data)=>api(path,{caseToken:token,...(data!==undefined?{method:'POST',data}:{})});
let current;
async function load(){current=await call('/api/portal');render(current);}
// The office name and logo come from the office settings.
api('/api/branding').then(b=>{if(b.office_name)$('#office-name').textContent=b.office_name;if(b.logo_version)$('.brand-mark').innerHTML=`<img src="${esc(window.PORTAL_CONFIG.api)}/api/logo?v=${Number(b.logo_version)}" alt="">`;}).catch(()=>{});
function render(c){const locked=['closed','archived'].includes(c.status),missing=c.requirements.filter(r=>r.status==='correction'||r.required&&!['uploaded','approved'].includes(r.status));app.innerHTML=`<section class="welcome"><span class="eyebrow">שלום ${esc(c.client_name)}</span><div class="card-head"><h1>${esc(c.name)}</h1>${badge(c.status)}</div><dl class="meta-grid"><div><dt>תקופת הדיווח</dt><dd>${esc(c.reporting_period)}</dd></div><div><dt>תאריך יעד להעברת החומרים</dt><dd>${date(c.due_date)}</dd></div></dl><p>אפשר להעלות בהדרגה ולחזור לקישור הזה בכל זמן.</p>${progress(c)}</section>${c.status==='client_completed'?'<section class="success done-state" role="status"><h2>כל המסמכים נשלחו למשרד</h2><p>המשרד יבדוק אותם ויעדכן אם צריך תיקון. אין צורך לעשות דבר נוסף כרגע.</p></section>':c.status==='ready_for_work'?'<p class="success">כל המסמכים נבדקו ואושרו. התיק מוכן לטיפול.</p>':''}${locked?'<p class="pending-note">התיק סגור. לצורך שינוי אפשר לפנות למשרד.</p>':''}${c.requirements.map(r=>{const pending=r.uploads.some(u=>u.state==='pending'),stored=r.uploads.filter(u=>u.state==='stored').length;return `<section class="panel card" data-requirement="${r.requirement_id}"><div class="card-head"><div><h3>${esc(r.name)}</h3><small>${r.required?'מסמך חובה':'רשות'}${r.max_files>1?' · עד '+r.max_files+' קבצים':''}</small></div>${badge(r.status)}</div>${r.correction_message?`<p class="review-note"><strong>הערה מהמשרד:</strong> ${esc(r.correction_message)}</p>`:''}<ul class="file-list">${r.uploads.map(u=>`<li><div>${esc(u.filename)}<small>גרסה ${u.version} · ${date(u.created_at)} · ${status[u.state]}</small></div><span>${Math.ceil(u.size/1024)} KB</span></li>`).join('')}</ul>${pending?'<p class="pending-note">ממתינים לאישור שמירת הקובץ. אין צורך להעלות שוב. אפשר לרענן בעוד רגע.</p>':!locked&&r.status!=='approved'&&(r.status==='correction'||stored<r.max_files)?`<form class="upload-zone" data-upload="${r.requirement_id}"><label>${r.status==='correction'?'העלאת גרסה מתוקנת':'בחירת מסמכים'}<input type="file" accept=".pdf,.png,.jpg,.jpeg" ${r.max_files>1&&r.status!=='correction'?'multiple':''} required aria-label="העלאת ${esc(r.name)}"></label><small>PDF, JPG או PNG · עד 4MB לכל קובץ</small><button class="primary">${r.status==='correction'?'שליחת התיקון למשרד לבדיקה':'שליחת המסמך למשרד לבדיקה'}</button><p class="upload-status" role="status"></p></form>`:''}</section>`;}).join('')}${locked||['client_completed','ready_for_work'].includes(c.status)?'':`<div class="sticky-finish"><p>${missing.length?'נותרו '+missing.length+' מסמכי חובה או תיקונים לשליחה.':'כל מסמכי החובה נשלחו. אפשר לסיים.'}<br><span class="muted">האישור הסופי יינתן לאחר בדיקת המשרד.</span></p><button id="finish" class="primary" ${missing.length?'disabled':''}>סיימתי לשלוח את כל המסמכים</button></div>`}<p class="client-bottom"><button id="refresh">רענון מצב המסמכים</button><br>הקישור אישי לתיק הזה. אין צורך להזין שוב פרטים.</p>`;
$('#refresh').onclick=()=>load().catch(e=>toast(e.message));if($('#finish'))$('#finish').onclick=async()=>{const b=$('#finish');b.disabled=true;try{await call('/api/portal/complete',{});location.reload();}catch(e){toast(e.message);b.disabled=false;}};
document.querySelectorAll('[data-upload]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button'),input=form.querySelector('input'),message=form.querySelector('.upload-status'),r=c.requirements.find(r=>r.requirement_id===form.dataset.upload),files=[...input.files],stored=r.uploads.filter(u=>u.state==='stored').length;if(files.length>(r.status==='correction'?1:r.max_files-stored)){message.textContent='נבחרו יותר קבצים מהמותר בדרישה.';return;}b.disabled=true;input.disabled=true;try{for(const file of files){if(file.size>4*1024*1024)throw new Error('הקובץ גדול מ־4MB.');message.textContent='שומר את '+file.name+'…';const fingerprint=[r.requirement_id,file.name,file.size,file.lastModified].join(':'),storageKey='upload:'+fingerprint;let id=sessionStorage.getItem(storageKey);if(!id){id=crypto.randomUUID();sessionStorage.setItem(storageKey,id);}const data=new FormData();data.set('file',file);data.set('requirement_id',r.requirement_id);data.set('submission_id',id);const result=await call('/api/portal/uploads',data);if(result.status!=='stored'){toast('הקובץ ממתין לאישור שמירה. אין להעלות שוב.');break;}sessionStorage.removeItem(storageKey);}await load();}catch(error){message.textContent=error.message;b.disabled=false;input.disabled=false;}});}
if(!/^[a-f0-9]{64}$/.test(token))app.innerHTML='<section class="panel card"><h1>נדרש קישור אישי</h1><p>פתחו את הקישור שקיבלתם מהמשרד כדי לראות את מסמכי התיק.</p></section>';else load().catch(e=>{app.innerHTML=`<section class="panel card"><h1>לא ניתן לפתוח את התיק</h1><p>${esc(e.message)}</p><button id="retry">ניסיון נוסף</button></section>`;$('#retry').onclick=()=>location.reload();});
