export const $=s=>document.querySelector(s);
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Office words name the next step and who owns it. The client sees the same states from their side (clientStatus).
export const status={collecting:'ממתין ללקוח',action_required:'נדרש תיקון',client_completed:'מוכן לבדיקה',ready_for_work:'המסמכים אושרו',closed:'בארכיון',archived:'בארכיון',missing:'חסר',uploaded:'מחכה לבדיקה',correction:'נדרש תיקון',approved:'אושר',pending:'ממתין לאישור שמירה',stored:'נשמר',failed:'השמירה נכשלה'};
export const clientStatus={...status,collecting:'מחכים למסמכים שלך',client_completed:'נשלח למשרד',ready_for_work:'אושר',uploaded:'נשלח, בבדיקה'};
export const badge=(s,words=status)=>`<span class="badge ${['approved','ready_for_work'].includes(s)?'green':['correction','action_required'].includes(s)?'red':['uploaded','client_completed'].includes(s)?'blue':'amber'}">${esc(words[s]||s)}</span>`;
// Every date reads DD/MM/YYYY, whatever the browser language. A plain date stays as written; a timestamp shows the Israeli day.
const DAY=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jerusalem',day:'2-digit',month:'2-digit',year:'numeric'});
export const date=s=>!s?'—':/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('/'):isNaN(Date.parse(s))?'—':DAY.format(new Date(s));
// Date fields: the visible field takes DD/MM/YYYY; the real value (YYYY-MM-DD) sits in a hidden date input that carries the
// field's name or id, so forms and filters read it as before. The calendar button opens the browser's own picker.
export const toDMY=iso=>/^\d{4}-\d{2}-\d{2}$/.test(iso||'')?iso.split('-').reverse().join('/'):'';
export function fromDMY(text){const m=String(text).trim().match(/^(\d{1,2})[/.-](\d{1,2})[/.-](\d{4})$/);if(!m)return '';const iso=`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`,d=new Date(iso+'T00:00:00Z');return d.getUTCDate()===+m[1]&&d.getUTCMonth()+1===+m[2]?iso:'';}
export function dateInput(attrs,iso='',required=false){return `<span class="date-field"><input type="text" class="date-text" inputmode="numeric" dir="ltr" placeholder="DD/MM/YYYY" maxlength="10" autocomplete="off" value="${toDMY(iso)}" ${required?'required':''}><input type="date" class="date-real" tabindex="-1" aria-hidden="true" ${attrs} value="${esc(iso)}"><button type="button" class="date-pick" aria-label="בחירה מלוח שנה">📅</button></span>`;}
export function setDate(real,iso){real.value=iso;const t=real.closest('.date-field')?.querySelector('.date-text');if(t){t.value=toDMY(iso);t.setCustomValidity('');}}
export function bindDates(root=document){root.querySelectorAll('.date-field:not([data-bound])').forEach(f=>{f.dataset.bound='1';const t=f.querySelector('.date-text'),r=f.querySelector('.date-real');
 const changed=()=>r.dispatchEvent(new Event('input',{bubbles:true}));
 t.addEventListener('input',()=>{const digits=t.value.replace(/\D/g,'');if(!t.value.includes('/')&&digits.length===8)t.value=digits.slice(0,2)+'/'+digits.slice(2,4)+'/'+digits.slice(4);
  const iso=fromDMY(t.value);t.setCustomValidity(t.value&&!iso?'תאריך בפורמט DD/MM/YYYY, למשל 04/10/2026':'');if(iso||!t.value){r.value=iso;changed();}});
 r.addEventListener('change',()=>{setDate(r,r.value);changed();});
 f.querySelector('.date-pick').onclick=()=>{try{r.showPicker();}catch{r.focus();}};});}
export const errors={unauthorized:'פרטי הכניסה אינם תקינים או שפג תוקף הכניסה.',too_many_attempts:'בוצעו יותר מדי ניסיונות כניסה. יש להמתין 15 דקות.',duplicate_reference:'מספר הלקוח כבר קיים.',invalid_fields:'יש לבדוק את השדות ולנסות שוב.',invalid_due_date:'תאריך היעד אינו תקין.',integration_not_ready:'חיבור שמירת הקבצים טרם הופעל. אפשר לפנות למשרד.',storage_unconfirmed:'טרם התקבל אישור שמירה. הקובץ ייבדק לפי מזהה ההגשה.',upload_pending:'קיימת העלאה שממתינה לאישור. המשרד יכול לבדוק את השמירה.',max_files:'הגעתם למספר הקבצים המותר בדרישה זו.',already_approved:'המסמך כבר אושר.',missing_requirements:'יש להשלים את מסמכי החובה ואת התיקונים.',case_closed:'התיק בארכיון ונעול להעלאות.',invalid_file:'יש לבחור PDF, PNG או JPG עד 4MB.',invalid_file_type:'סוג הקובץ אינו נתמך.',invalid_file_signature:'תוכן הקובץ אינו תואם לסוג שלו.',not_configured:'המערכת עדיין אינה מוגדרת לשימוש.',not_found:'הפריט לא נמצא.',nothing_missing:'לא נותרו מסמכים חסרים.',internal_error:'הפעולה לא הושלמה. נסו שוב.',submission_conflict:'מזהה ההגשה כבר שויך לקובץ אחר.',storage_failed:'שמירת הקובץ נכשלה. אפשר לנסות להעלות שוב.',requirements_required:'יש לבחור לפחות מסמך אחד לתיק.',mandatory_requirement_required:'לפחות מסמך אחד צריך להיות חובה.',client_not_found:'הלקוח לא נמצא. יש לבחור לקוח מהרשימה.',invalid_deadline_days:'ימי ההתרעה אינם תקינים. ההתרעה האדומה צריכה להיות קרובה יותר מהצהובה.',invalid_template_placeholder:'בנוסח התזכורת יש שדה לא מוכר בסוגריים מסולסלים.',logo_too_large:'קובץ הלוגו גדול מ־200KB.',conflict:'הפעולה התנגשה בשינוי אחר. נסו שוב.',forbidden:'הפעולה הזו שמורה למנהל המשרד.',weak_password:'הסיסמה צריכה להיות באורך 8 תווים לפחות.',wrong_password:'הסיסמה הנוכחית שגויה.',duplicate_email:'כבר יש איש צוות עם הדוא״ל הזה.',last_admin:'חייב להישאר לפחות מנהל משרד פעיל אחד.',already_set_up:'המשרד כבר הוגדר. נכנסים עם דוא״ל וסיסמה.',staff_not_found:'איש הצוות לא נמצא או שאינו פעיל.',invalid_email:'כתובת הדוא״ל אינה תקינה.',nothing_to_review:'אין מסמכים שמחכים לבדיקה.',invalid_phone:'מספר הטלפון אינו תקין. נדרש נייד ישראלי (05X) או מספר בינלאומי שמתחיל ב־+.',pin_required:'יש להקיש את 4 הספרות האחרונות של הנייד.',wrong_pin:'הספרות לא נכונות. בודקים את 4 הספרות האחרונות של הנייד שמסרתם למשרד.',consent_required:'כדי שנחזור אליך צריך לסמן את האישור.',invalid_mobile:'מספר נייד צריך להכיל 10 ספרות ולהתחיל ב־05.',not_missing:'אפשר לסמן רק מסמך שעוד לא נשלח.',template_not_found:'סוג התיק לא נמצא.',duplicate_document:'המסמך כבר מופיע ברשימה.',email_maybe_sent:'לא התקבל אישור מהשרת. ייתכן שהמייל כבר נשלח, אז כדאי לבדוק בדואר היוצא של contact@waives.io לפני שליחה חוזרת.',no_preview:'אין תצוגה לקובץ הזה.',reason_required:'כתבו בכמה מילים למה אין לכם את המסמך.',email_failed:'המייל לא נשלח. אפשר לשלוח ב־WhatsApp או להעתיק את ההודעה.'};
export function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),5000);}
export async function api(path,{method='GET',data,token,caseToken,pin}={}){const headers={};if(token)headers.Authorization='Bearer '+token;if(caseToken)headers['X-Case-Token']=caseToken;if(pin)headers['X-Case-Pin']=pin;let body;if(data instanceof FormData)body=data;else if(data!==undefined){headers['Content-Type']='application/json';body=JSON.stringify(data);}let response;try{response=await fetch(window.PORTAL_CONFIG.api+path,{method,headers,body,cache:'no-store'});}catch{throw new Error('אין חיבור לשרת. בדקו את החיבור ונסו שוב.');}const result=await response.json();if(!response.ok){const e=new Error(errors[result.error]||result.error);e.code=result.error;throw e;}return result;}
export function field(name,label,type='text',value='',required=false){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;}
export function dialog(title,content){const m=$('#modal');m.innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button type="button" id="close-modal" aria-label="סגירה">×</button></div>${content}<p id="form-error" class="error" role="alert"></p>`;$('#close-modal').onclick=()=>m.close();m.showModal();return m;}
export function bindForm(selector,fn){$(selector).onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await fn(Object.fromEntries(new FormData(e.target)),e.target);}catch(error){const p=$('#form-error')||$('#login-error');if(p)p.textContent=error.message;else toast(error.message);}finally{b.disabled=false;}};}
// The server decides what progress means: documents sent while collecting, documents approved once the client is done.
// One bar in two shades: received (light) and approved (dark), out of the documents that matter. The same count on every screen.
// The office says "התקבלו", the client says "נשלחו". The bar is SVG because the page policy blocks inline styles.
export function progress(c,side='office'){const total=Number(c.docs_total)||0,got=Number(c.docs_received)||0,ok=Number(c.docs_approved)||0,w=n=>total?Math.round(100*n/total):0;
 const text=`${got} מתוך ${total} ${side==='client'?'נשלחו':'התקבלו'} · ${ok} אושרו`;
 return `<div class="progress-label"><strong>${text}</strong></div><svg class="duo-bar" viewBox="0 0 100 8" preserveAspectRatio="none" role="img" aria-label="${text}"><rect class="duo-bg" width="100" height="8" rx="4"/><rect class="duo-got" x="${100-w(got)}" width="${w(got)}" height="8" rx="4"/><rect class="duo-ok" x="${100-w(ok)}" width="${w(ok)}" height="8" rx="4"/></svg>`;}
export function deadlineLabel(c){if(!c.deadline||c.deadline==='none'||c.deadline==='ok')return '';const d=c.days_left;const text=d<0?`באיחור של ${-d===1?'יום':-d+' ימים'}`:d===0?'היום יעד':d===1?'מחר יעד':d===2?'עוד יומיים':`עוד ${d} ימים`;return `<span class="deadline" data-deadline="${esc(c.deadline)}">${text}</span>`;}
