export const $=s=>document.querySelector(s);
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const status={collecting:'באיסוף מסמכים',action_required:'נדרשת השלמה',client_completed:'ממתין לבדיקת המשרד',ready_for_work:'מוכן לטיפול',closed:'סגור',archived:'בארכיון',missing:'חסר',uploaded:'הועלה',correction:'נדרש תיקון',approved:'אושר',pending:'ממתין לאישור שמירה',stored:'נשמר'};
export const badge=s=>`<span class="badge ${['approved','ready_for_work'].includes(s)?'green':['correction','action_required'].includes(s)?'red':['uploaded','client_completed'].includes(s)?'blue':'amber'}">${esc(status[s]||s)}</span>`;
export const date=s=>s?new Date(s).toLocaleDateString('he-IL'):'—';
export const errors={unauthorized:'פרטי הכניסה אינם תקינים או שפג תוקף הכניסה.',too_many_attempts:'בוצעו יותר מדי ניסיונות כניסה. יש להמתין 15 דקות.',duplicate_reference:'מספר הלקוח כבר קיים.',invalid_fields:'יש לבדוק את השדות ולנסות שוב.',invalid_due_date:'תאריך היעד אינו תקין.',integration_not_ready:'חיבור שמירת הקבצים טרם הופעל. אפשר לפנות למשרד.',storage_unconfirmed:'טרם התקבל אישור שמירה. הקובץ ייבדק לפי מזהה ההגשה.',upload_pending:'קיימת העלאה שממתינה לאישור. המשרד יכול לבדוק את השמירה.',max_files:'הגעתם למספר הקבצים המותר בדרישה זו.',already_approved:'המסמך כבר אושר.',missing_requirements:'יש להשלים את מסמכי החובה ואת התיקונים.',case_closed:'המקרה סגור להעלאות.',invalid_file:'יש לבחור PDF, PNG או JPG עד 4MB.',invalid_file_type:'סוג הקובץ אינו נתמך.',invalid_file_signature:'תוכן הקובץ אינו תואם לסוג שלו.',not_configured:'המערכת עדיין אינה מוגדרת לשימוש.',not_found:'הפריט לא נמצא.',nothing_missing:'לא נותרו מסמכים חסרים.',internal_error:'הפעולה לא הושלמה. נסו שוב.',submission_conflict:'מזהה ההגשה כבר שויך לקובץ אחר.'};
export function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),5000);}
export async function api(path,{method='GET',data,token,caseToken}={}){const headers={};if(token)headers.Authorization='Bearer '+token;if(caseToken)headers['X-Case-Token']=caseToken;let body;if(data instanceof FormData)body=data;else if(data!==undefined){headers['Content-Type']='application/json';body=JSON.stringify(data);}let response;try{response=await fetch(window.PORTAL_CONFIG.api+path,{method,headers,body,cache:'no-store'});}catch{throw new Error('אין חיבור לשרת. בדקו את החיבור ונסו שוב.');}const result=await response.json();if(!response.ok)throw new Error(errors[result.error]||result.error);return result;}
export function field(name,label,type='text',value='',required=false){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;}
export function dialog(title,content){const m=$('#modal');m.innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button type="button" id="close-modal" aria-label="סגירה">×</button></div>${content}<p id="form-error" class="error" role="alert"></p>`;$('#close-modal').onclick=()=>m.close();m.showModal();return m;}
export function bindForm(selector,fn){$(selector).onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await fn(Object.fromEntries(new FormData(e.target)),e.target);}catch(error){const p=$('#form-error')||$('#login-error');if(p)p.textContent=error.message;else toast(error.message);}finally{b.disabled=false;}};}
export function progress(c){const done=c.requirements?c.requirements.filter(r=>['uploaded','approved'].includes(r.status)).length:c.received;const total=c.requirements?c.requirements.length:c.total;return `<div class="progress-label"><span>התקדמות המסמכים</span><strong>${done} מתוך ${total}</strong></div><progress max="${total||1}" value="${done}" aria-label="התקדמות המסמכים"></progress>`;}
