import {$,esc,status,badge,date,toast,api,field,dialog,bindForm,progress,deadlineLabel} from './common.mjs';
let token=sessionStorage.getItem('office_session')||'',cases=[],clients=[],catalog=[],templates=[],settings={},view='cases',statusFilter='active';
const call=(path,data)=>api(path,{token,...(data!==undefined?{method:'POST',data}:{})});
const app=$('#app');
const ACTIVE=['collecting','action_required','client_completed','ready_for_work'];
const clientLabel=c=>`${c.name} · ${c.reference}`;
const caseCount=id=>cases.filter(x=>x.client_id===id).length;

function login(){app.innerHTML=`<section class="panel login"><span class="eyebrow">סביבת המשרד</span><h1>נכנסים לתיק מוכן</h1><p class="muted">כניסה לצוות המשרד באמצעות קוד המשרד.</p><form id="login">${field('code','קוד כניסה','password','',true)}<button class="primary">כניסה למשרד</button><p id="login-error" class="error" role="alert"></p></form></section>`;bindForm('#login',async b=>{const r=await api('/api/login',{method:'POST',data:b});token=r.token;sessionStorage.setItem('office_session',token);await load();});}

function applyBranding(b){if(b.office_name)$('#office-name').textContent=b.office_name;const mark=$('.brand-mark');mark.innerHTML=b.logo_version?`<img src="${esc(window.PORTAL_CONFIG.api)}/api/logo?v=${Number(b.logo_version)}" alt="">`:'✓';}
async function load(){[cases,clients,catalog,templates,settings]=await Promise.all(['/api/cases','/api/clients','/api/catalog','/api/templates','/api/settings'].map(p=>call(p)));applyBranding(settings);$('#logout').hidden=false;render();}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));({cases:renderCases,clients:renderClients,documents:renderDocuments,templates:renderTemplates,settings:renderSettings}[view]||renderCases)();}
const options=(values,empty='הכול')=>`<option value="">${empty}</option>`+[...new Set(values)].filter(Boolean).map(v=>`<option>${esc(v)}</option>`).join('');

// Dashboard tiles are the status filter. Their labels are the same words as the status badges.
const tiles=[{key:'active',label:'תיקים פעילים',match:c=>ACTIVE.includes(c.status)},...ACTIVE.map(s=>({key:s,label:status[s],match:c=>c.status===s}))];
const statusMatch=c=>statusFilter==='all'||(tiles.find(t=>t.key===statusFilter)?.match||(x=>x.status===statusFilter))(c);

async function sendWhatsapp(id){
 // Open the tab synchronously so the browser does not block it, then point it at WhatsApp once the text is ready.
 const w=window.open('about:blank','_blank');
 try{const r=await call('/api/cases/'+id+'/reminder',{});if(!/^\d{11,15}$/.test(r.whatsapp||''))throw new Error('אין ללקוח מספר נייד תקין.');const url=new URL('https://wa.me/'+r.whatsapp);url.searchParams.set('text',r.text);if(w){w.opener=null;w.location.href=url.href;}else location.href=url.href;}
 catch(e){w?.close();toast(e.message);}
}
const whatsappButton=c=>['urgent','overdue'].includes(c.deadline)&&c.whatsapp?`<button type="button" data-whatsapp="${esc(c.case_id)}">תזכורת בוואטסאפ</button>`:'';

function renderCases(){app.innerHTML=`<div class="page-heading"><div><span class="eyebrow">סביבת המשרד</span><h1>כל תיק. כל המסמכים.</h1><p>תמונת המצב של החומרים, ההשלמות והבדיקות.</p></div><div class="actions"><button class="primary" id="new-case">＋ תיק חדש</button></div></div>
<div class="stats">${tiles.map(t=>`<button type="button" class="stat" data-tile="${t.key}" aria-pressed="${statusFilter===t.key}"><span>${esc(t.label)}</span><strong>${cases.filter(t.match).length}</strong></button>`).join('')}</div>
<div class="filters"><label>חיפוש<input id="search" placeholder="שם לקוח, מספר לקוח או תיק"></label><label>סטטוס<select id="status"><option value="all">כל התיקים</option>${tiles.map(t=>`<option value="${t.key}">${esc(t.label)}</option>`).join('')}${['closed','archived'].map(s=>`<option value="${s}">${status[s]}</option>`).join('')}</select></label><label>קטגוריה<select id="category">${options(cases.map(c=>c.category))}</select></label><label>תקופת דיווח<select id="period">${options(cases.map(c=>c.reporting_period))}</select></label><label>יעד עד לתאריך<input type="date" id="due"></label><label>אחראי<select id="owner">${options(cases.map(c=>c.owner))}</select></label></div>
<section class="panel table-wrap"><table><thead><tr><th>לקוח / תיק</th><th>תקופת דיווח</th><th>תאריך יעד</th><th>התקדמות</th><th>סטטוס</th><th>אחראי</th><th>פעילות אחרונה</th></tr></thead><tbody id="rows"></tbody></table><div id="empty" class="empty" hidden>אין תיקים להצגה. אפשר לפתוח תיק חדש או לשנות את הסינון.</div><div id="client-hits"></div></section>`;
 $('#status').value=statusFilter;
 const filter=()=>{const q=$('#search').value.trim().toLowerCase();
  const rows=cases.filter(c=>[c.client_name,c.reference,c.case_id,c.name].join(' ').toLowerCase().includes(q)&&statusMatch(c)&&(!$('#category').value||c.category===$('#category').value)&&(!$('#period').value||c.reporting_period===$('#period').value)&&(!$('#due').value||c.due_date<=$('#due').value)&&(!$('#owner').value||c.owner===$('#owner').value));
  $('#rows').innerHTML=rows.map(c=>`<tr data-deadline="${esc(c.deadline)}"><td><button class="case-name" data-case="${esc(c.case_id)}"><strong>${esc(c.client_name)}</strong>${esc(c.name)}</button><small>${esc(c.reference)} · <span class="mono">${esc(c.case_id.slice(0,8))}</span></small></td><td>${esc(c.reporting_period)}</td><td>${date(c.due_date)}${deadlineLabel(c)}${whatsappButton(c)}</td><td>${progress(c)}<small>${esc(c.missing||'כל המסמכים התקבלו')}</small></td><td>${badge(c.status)}</td><td>${esc(c.owner||'—')}</td><td>${date(c.last_activity)}</td></tr>`).join('');
  $('#empty').hidden=rows.length>0;
  // A search for a client who has no matching case should still lead somewhere: offer to open a case for them.
  const shown=new Set(rows.map(c=>c.client_id)),hits=q?clients.filter(c=>!shown.has(c.client_id)&&[c.name,c.reference].join(' ').toLowerCase().includes(q)).slice(0,5):[];
  $('#client-hits').innerHTML=hits.length?`<p class="muted">לקוחות שנמצאו בחיפוש בלי תיק מתאים:</p><ul class="file-list">${hits.map(c=>`<li><div><strong>${esc(c.name)}</strong><small>${esc(c.reference)} · ${caseCount(c.client_id)} תיקים</small></div><button type="button" data-new-for="${esc(c.client_id)}">פתיחת תיק</button></li>`).join('')}</ul>`:'';
  document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>showCase(b.dataset.case).catch(e=>toast(e.message)));
  document.querySelectorAll('[data-whatsapp]').forEach(b=>b.onclick=()=>sendWhatsapp(b.dataset.whatsapp));
  document.querySelectorAll('[data-new-for]').forEach(b=>b.onclick=()=>newCase(b.dataset.newFor));
  document.querySelectorAll('[data-tile]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tile===statusFilter)));};
 document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{statusFilter=statusFilter===b.dataset.tile?'all':b.dataset.tile;$('#status').value=statusFilter;filter();});
 $('#status').oninput=()=>{statusFilter=$('#status').value;filter();};
 document.querySelectorAll('.filters input,.filters select:not(#status)').forEach(i=>i.oninput=filter);filter();
 $('#new-case').onclick=()=>newCase();}

function clientForm(selected,after){const c=selected||{};dialog(c.client_id?'עריכת לקוח':'לקוח חדש',`<form id="client-form"><div class="form-grid">${field('name','שם מלא או שם עסק','text',c.name||'',true)}${field('reference','מספר לקוח','text',c.reference||'',true)}${field('business_number','מספר חברה / עוסק','text',c.business_number||'')}${field('email','דוא״ל','email',c.email||'')}${field('phone','טלפון נייד','tel',c.phone||'')}${field('tags','תגיות','text',c.tags||'')}${field('status','סטטוס לקוח','text',c.status||'active')}<label class="wide">הערות<textarea name="notes">${esc(c.notes||'')}</textarea></label></div><button class="primary">שמירת לקוח</button></form>`);
 bindForm('#client-form',async b=>{const r=await call(c.client_id?'/api/clients/'+c.client_id:'/api/clients',b);$('#modal').close();await load();toast('הלקוח נשמר');if(after)after(r.client_id);});}

function renderClients(){app.innerHTML=`<div class="page-heading"><div><span class="eyebrow">אנשי הקשר של המשרד</span><h1>לקוחות</h1><p>רשומה אחת לכל לקוח, גם כשיש כמה תיקים.</p></div><button class="primary" id="new-client">＋ לקוח חדש</button></div><div class="filters"><label>חיפוש<input id="client-search" placeholder="שם, מספר לקוח, טלפון או דוא״ל"></label></div><section class="panel table-wrap"><table><thead><tr><th>שם</th><th>מספר לקוח</th><th>דוא״ל</th><th>טלפון</th><th>תיקים</th><th></th></tr></thead><tbody id="client-rows"></tbody></table>${clients.length?'':'<div class="empty">עדיין אין לקוחות. מתחילים ביצירת לקוח.</div>'}</section>`;
 const draw=()=>{const q=$('#client-search').value.trim().toLowerCase();$('#client-rows').innerHTML=clients.filter(c=>[c.name,c.reference,c.phone,c.email].join(' ').toLowerCase().includes(q)).map(c=>`<tr><td><button class="case-name" data-client="${esc(c.client_id)}"><strong>${esc(c.name)}</strong></button><small>${esc(c.tags)}</small></td><td>${esc(c.reference)}</td><td>${esc(c.email)}</td><td>${esc(c.phone)}</td><td>${caseCount(c.client_id)}</td><td><div class="actions"><button data-edit-client="${esc(c.client_id)}">עריכה</button><button data-new-for="${esc(c.client_id)}">פתיחת תיק</button></div></td></tr>`).join('');
  document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>showClient(b.dataset.client));
  document.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>clientForm(clients.find(c=>c.client_id===b.dataset.editClient)));
  document.querySelectorAll('[data-new-for]').forEach(b=>b.onclick=()=>newCase(b.dataset.newFor));};
 $('#client-search').oninput=draw;draw();$('#new-client').onclick=()=>clientForm();}

// The client record shows every case with its personal link, so the office can resend a link a client lost.
function showClient(id){const c=clients.find(x=>x.client_id===id),own=cases.filter(x=>x.client_id===id);
 app.innerHTML=`<button class="back-button" id="back">→ לכל הלקוחות</button><div class="page-heading"><div><span class="eyebrow">${esc(c.reference)}</span><h1>${esc(c.name)}</h1><p>${esc(c.tags)}</p></div><div class="actions"><button id="edit-client">עריכת פרטים</button><button class="primary" id="client-new-case">＋ תיק חדש</button></div></div><div class="detail-grid"><div><section class="panel card"><h2>התיקים של הלקוח</h2><ul class="file-list">${own.map(x=>`<li><div><button class="case-name" data-case="${esc(x.case_id)}"><strong>${esc(x.name)}</strong></button><small>${esc(x.reporting_period)} · יעד ${date(x.due_date)} · ${esc(status[x.status])}</small></div><button data-link="${esc(x.case_id)}">קישור אישי ללקוח</button></li>`).join('')||'<li class="muted">אין תיקים ללקוח הזה.</li>'}</ul></section></div><aside><section class="panel card"><h3>פרטי הלקוח</h3><dl class="meta-grid"><div><dt>מספר חברה / עוסק</dt><dd>${esc(c.business_number||'—')}</dd></div><div><dt>דוא״ל</dt><dd>${esc(c.email||'—')}</dd></div><div><dt>טלפון</dt><dd>${esc(c.phone||'—')}</dd></div><div><dt>סטטוס</dt><dd>${esc(c.status||'—')}</dd></div></dl>${c.notes?`<p>${esc(c.notes)}</p>`:''}</section></aside></div>`;
 $('#back').onclick=()=>{view='clients';render();};$('#edit-client').onclick=()=>clientForm(c,()=>showClient(id));$('#client-new-case').onclick=()=>newCase(id);
 document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>showCase(b.dataset.case).catch(e=>toast(e.message)));
 document.querySelectorAll('[data-link]').forEach(b=>b.onclick=()=>openLink(b.dataset.link));}

// One editor for the documents of a template and of a case. Each row says one thing: required or optional, and how many files.
// A name that is not in the library is still allowed; a template adds it to the library when saved.
function rowHtml(i){return `<div class="check-row" data-document="${esc(i.document_id||'')}" data-name="${esc(i.name)}"><span>${esc(i.name)}</span><label>סוג<select class="required"><option value="1" ${i.required?'selected':''}>חובה</option><option value="0" ${i.required?'':'selected'}>רשות</option></select></label><label>מספר קבצים<input type="number" class="max" min="1" max="20" value="${Number(i.max_files)||1}"></label><button type="button" class="remove" aria-label="הסרת ${esc(i.name)}">×</button></div>`;}
function rowsEditor(items){return `<div class="requirement-editor" id="req-rows">${items.map(rowHtml).join('')}</div><p class="muted" id="no-rows" ${items.length?'hidden':''}>עדיין לא נבחרו מסמכים.</p><div class="add-document"><label>הוספת מסמך<input id="doc-search" list="doc-options" placeholder="לבחור מהרשימה או להקליד שם של מסמך חדש" autocomplete="off"></label><datalist id="doc-options"></datalist><button type="button" id="add-doc">＋ הוספה</button></div>`;}
function bindRows(){const box=$('#req-rows'),names=()=>new Set([...box.querySelectorAll('[data-name]')].map(r=>r.dataset.name.trim().toLowerCase()));
 const refresh=()=>{const used=names();$('#doc-options').innerHTML=catalog.filter(c=>c.active&&!used.has(c.name.trim().toLowerCase())).map(c=>`<option value="${esc(c.name)}">`).join('');$('#no-rows').hidden=used.size>0;};
 const add=()=>{const name=$('#doc-search').value.trim();if(!name){toast('יש לבחור מסמך או להקליד שם.');return;}if(names().has(name.toLowerCase())){toast('המסמך כבר ברשימה.');return;}const doc=catalog.find(c=>c.name.trim().toLowerCase()===name.toLowerCase());box.insertAdjacentHTML('beforeend',rowHtml({document_id:doc?.document_id,name:doc?.name||name,required:true,max_files:1}));$('#doc-search').value='';refresh();};
 box.onclick=e=>{if(e.target.classList.contains('remove')){e.target.closest('.check-row').remove();refresh();}};
 $('#add-doc').onclick=add;$('#doc-search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();add();}};refresh();}
function selectedItems(){return [...document.querySelectorAll('#req-rows [data-name]')].map(r=>({...(r.dataset.document?{document_id:r.dataset.document}:{}),name:r.dataset.name,required:r.querySelector('.required').value==='1',max_files:Math.min(20,Math.max(1,Number(r.querySelector('.max').value)||1))}));}

// Each field has an example, so the office knows what to type.
function newCase(clientId=''){const pre=clients.find(c=>c.client_id===clientId),categories=[...new Set(['עצמאי','חברה בע״מ','שכיר','עמותה',...cases.map(c=>c.category)])].filter(Boolean);
 dialog('פתיחת תיק',`<form id="case-form"><div class="form-grid"><label class="wide">לקוח<input id="client-pick" list="client-options" placeholder="הקלדת שם או מספר לקוח" autocomplete="off" required value="${esc(pre?clientLabel(pre):'')}"></label><datalist id="client-options">${clients.map(c=>`<option value="${esc(clientLabel(c))}">`).join('')}</datalist><div class="wide"><button type="button" id="inline-client">＋ לקוח חדש</button></div>
<label class="wide">תבנית מסמכים<select id="template"><option value="">ללא תבנית, בחירה ידנית</option>${templates.map(t=>`<option value="${esc(t.template_id)}">${esc(t.name)}</option>`).join('')}</select><small class="muted">רשימת המסמכים הבסיסית. אפשר להוסיף ולהסיר מסמכים לתיק הזה בלבד, בלי לשנות את התבנית.</small></label>
<label class="wide">שם התיק<input name="name" required placeholder="לדוגמה: הנהלת חשבונות ספטמבר 2026"></label>
<label>סוג תיק<input name="type" id="case-type" required placeholder="לדוגמה: הנהלת חשבונות חודשית, דוח שנתי, הצהרת הון"><small class="muted">מתמלא לפי התבנית. אפשר לשנות.</small></label>
<label>קטגוריה<input name="category" list="category-options" placeholder="לדוגמה: עצמאי, חברה בע״מ"><small class="muted">לסינון ברשימת התיקים.</small></label><datalist id="category-options">${categories.map(c=>`<option value="${esc(c)}">`).join('')}</datalist>
<label>תקופת דיווח מתאריך<input type="date" name="period_start" required></label><label>עד תאריך<input type="date" name="period_end" required></label>
<label>תאריך יעד להעברת החומרים<input type="date" name="due_date" required></label>
<label>אחראי במשרד<input name="owner" list="owner-options" placeholder="לדוגמה: מיכל"></label><datalist id="owner-options">${[...new Set(cases.map(c=>c.owner))].filter(Boolean).map(o=>`<option value="${esc(o)}">`).join('')}</datalist></div>
<div><h3>המסמכים שיידרשו מהלקוח</h3><div id="items"></div></div><button class="primary">יצירת תיק וקישור אישי</button></form>`);
 const showItems=t=>{$('#items').innerHTML=rowsEditor(t?.items||[]);bindRows();if(t)$('#case-type').value=t.name;};
 if(templates[0])$('#template').value=templates[0].template_id;showItems(templates[0]);
 $('#template').onchange=()=>showItems(templates.find(t=>t.template_id===$('#template').value));
 $('#inline-client').onclick=()=>clientForm(null,id=>newCase(id));
 bindForm('#case-form',async b=>{const client=clients.find(c=>clientLabel(c)===$('#client-pick').value.trim());if(!client)throw new Error('יש לבחור לקוח מהרשימה, או ליצור לקוח חדש.');if(b.period_start>b.period_end)throw new Error('תאריך הסיום של התקופה לפני תאריך ההתחלה.');b.client_id=client.client_id;b.requirements=selectedItems();const r=await call('/api/cases',b);$('#modal').close();await load();await showCase(r.case_id);linkDialog(r.link,r.case_id);});}

function linkDialog(link,caseId){const local=location.hostname==='localhost'||location.hostname==='127.0.0.1';if(local)link=location.origin+'/client.html#'+link.split('#')[1];
 dialog('הקישור האישי לתיק',`<p class="muted">הלקוח חוזר לאותו קישור בכל פעם. הקישור מאפשר גישה למסמכי התיק ויש לשתף אותו רק עם הלקוח.</p><p class="link-box">${esc(link)}</p><div class="actions"><button class="primary" id="copy-link">העתקת הקישור</button><a href="${esc(link)}" target="_blank" rel="noopener noreferrer">פתיחת פורטל הלקוח ↗</a></div><details><summary>הקישור הגיע למישהו אחר?</summary><p class="muted">אפשר לבטל את הקישור הזה וליצור ללקוח קישור חדש. הקישור הישן יפסיק לעבוד מיד.</p><button type="button" id="revoke-link">ביטול הקישור ויצירת קישור חדש</button></details>`);
 $('#copy-link').onclick=async()=>{await navigator.clipboard.writeText(link);toast('הקישור הועתק');};
 $('#revoke-link').onclick=async()=>{if(!confirm('לבטל את הקישור הנוכחי? הלקוח יצטרך לקבל את הקישור החדש.'))return;try{const r=await call('/api/cases/'+caseId+'/revoke-link',{});linkDialog(r.link,caseId);toast('נוצר קישור חדש. הקישור הישן בוטל.');}catch(e){toast(e.message);}};}
const openLink=async id=>{try{linkDialog((await call('/api/cases/'+id+'/link')).link,id);}catch(e){toast(e.message);}};

const events={case_created:'התיק נפתח',upload_stored:'מסמך נשמר',upload_stored_late:'מסמך נשמר באיחור',upload_failed:'שמירת מסמך נכשלה',client_completed:'הלקוח סיים לשלוח',approved:'דרישה אושרה',correction:'התבקש תיקון',reminder_prepared:'הוכנה תזכורת',case_status:'סטטוס התיק השתנה',link_revoked:'הקישור האישי הוחלף'};
async function showCase(id){const c=await call('/api/cases/'+id),locked=['closed','archived'].includes(c.status);
 app.innerHTML=`<button class="back-button" id="back">→ לכל התיקים</button><div class="page-heading"><div><span class="eyebrow">${esc(c.reference)} · <span class="mono">${esc(c.case_id)}</span></span><h1>${esc(c.client_name)}</h1><p>${esc(c.name)} ${badge(c.status)}</p></div><div class="actions"><button id="case-link">קישור אישי</button>${locked?'':`<button id="remind">הכנת תזכורת</button>`}${whatsappButton(c)}${locked?'<button class="primary" data-state="reopen">פתיחת התיק מחדש</button>':'<button class="primary" data-state="closed">סגירת תיק</button>'}</div></div>
<div class="detail-grid"><div><section class="panel card"><div class="card-head"><h2>מסמכי התיק</h2>${badge(c.status)}</div>${progress(c)}<dl class="meta-grid"><div><dt>תקופת דיווח</dt><dd>${esc(c.reporting_period)}</dd></div><div><dt>תאריך יעד</dt><dd>${date(c.due_date)} ${deadlineLabel(c)}</dd></div></dl></section>${c.requirements.map(r=>`<section class="panel card"><div class="card-head"><div><h3>${esc(r.name)}</h3><small>${r.required?'חובה':'רשות'}${r.max_files>1?' · עד '+r.max_files+' קבצים':''}</small></div>${badge(r.status)}</div>${r.correction_message?`<p class="review-note">${esc(r.correction_message)}</p>`:''}<ul class="file-list">${r.uploads.map(u=>`<li><div>${u.drive_file_id?`<a target="_blank" rel="noopener noreferrer" href="https://drive.google.com/file/d/${encodeURIComponent(u.drive_file_id)}/view">${esc(u.filename)} ↗</a>`:esc(u.filename)}<small>גרסה ${u.version} · ${date(u.created_at)} · ${status[u.state]}</small></div>${u.state==='pending'?`<button data-reconcile="${esc(u.submission_id)}">בדיקת שמירה</button>`:''}</li>`).join('')||'<li class="muted">טרם התקבל קובץ</li>'}</ul>${r.uploads.some(u=>u.state==='stored')&&!locked?`<div class="actions"><button data-approve="${esc(r.requirement_id)}" ${r.status==='approved'?'disabled':''}>אישור הדרישה ✓</button><button data-correct="${esc(r.requirement_id)}">נדרש תיקון</button></div>`:''}</section>`).join('')}</div>
<aside><section class="panel card"><h3>פרטי התיק</h3><dl class="meta-grid"><div><dt>אחראי</dt><dd>${esc(c.owner||'—')}</dd></div><div><dt>קטגוריה</dt><dd>${esc(c.category||'—')}</dd></div><div><dt>דוא״ל</dt><dd>${esc(c.email||'—')}</dd></div><div><dt>טלפון</dt><dd>${esc(c.phone||'—')}</dd></div></dl><p class="muted">סגירת תיק נועלת אותו להעלאות. אפשר לפתוח אותו מחדש בכל רגע.</p>${locked?'':'<div class="actions"><button data-state="archived">העברה לארכיון</button></div>'}</section><section class="panel activity"><h3>מה קרה בתיק</h3>${c.events.map(e=>`<div class="event"><span>${esc(events[e.action]||e.action)}<small>${esc(e.detail)}</small></span><time>${date(e.created_at)}</time></div>`).join('')}</section></aside></div>`;
 $('#back').onclick=()=>{view='cases';load().catch(e=>toast(e.message));};$('#case-link').onclick=()=>openLink(id);
 document.querySelectorAll('[data-whatsapp]').forEach(b=>b.onclick=()=>sendWhatsapp(b.dataset.whatsapp));
 if($('#remind'))$('#remind').onclick=async()=>{try{const r=await call('/api/cases/'+id+'/reminder',{});dialog('תזכורת להשלמת המסמכים',`<p class="muted">ההודעה מוכנה לשליחה ידנית. לא נשלחה הודעה.</p><textarea id="reminder-text" rows="10">${esc(r.text)}</textarea><div class="actions"><button id="copy-reminder" class="primary">העתקת הנוסח</button><a id="wa-link" target="_blank" rel="noopener noreferrer">הכנה ב־WhatsApp</a><a href="mailto:${encodeURIComponent(r.email)}?subject=${encodeURIComponent(r.subject)}&body=${encodeURIComponent(r.text)}">הכנה בדוא״ל</a></div>`);const wa=new URL('https://wa.me/'+(/^\d{11,15}$/.test(r.whatsapp||'')?r.whatsapp:''));wa.searchParams.set('text',r.text);$('#wa-link').href=wa.href;$('#copy-reminder').onclick=async()=>{await navigator.clipboard.writeText(r.text);toast('התזכורת הועתקה');};}catch(e){toast(e.message);}};
 const review=async(r,status,message='')=>{await call('/api/cases/'+id+'/review',{requirement_id:r,status,message});await showCase(id);};
 document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>review(b.dataset.approve,'approved').catch(e=>toast(e.message)));
 document.querySelectorAll('[data-correct]').forEach(b=>b.onclick=()=>{dialog('מה צריך לתקן?',`<form id="correction"><label>הסבר ללקוח<textarea name="message" required maxlength="1000"></textarea></label><button class="primary">בקשת תיקון</button></form>`);bindForm('#correction',async data=>{await review(b.dataset.correct,'correction',data.message);$('#modal').close();});});
 const confirmText={closed:'לסגור את התיק? הלקוח לא יוכל להעלות מסמכים עד שהתיק ייפתח מחדש.',archived:'להעביר את התיק לארכיון? הוא יינעל להעלאות.'};
 document.querySelectorAll('[data-state]').forEach(b=>b.onclick=async()=>{if(confirmText[b.dataset.state]&&!confirm(confirmText[b.dataset.state]))return;try{await call('/api/cases/'+id+'/status',{status:b.dataset.state});await showCase(id);}catch(e){toast(e.message);}});
 document.querySelectorAll('[data-reconcile]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await call('/api/cases/'+id+'/reconcile',{submission_id:b.dataset.reconcile});await showCase(id);}catch(e){toast(e.message);b.disabled=false;}});}

// The document library is secondary: documents are added inside templates. This page only renames or retires them.
function renderDocuments(){app.innerHTML=`<button class="back-button" id="back">→ לתבניות</button><div class="page-heading"><div><span class="eyebrow">הגדרות המשרד</span><h1>ספריית המסמכים</h1><p>כל המסמכים שהופיעו בתבניות. מסמך חדש נוסף לכאן אוטומטית כשמוסיפים אותו לתבנית.</p></div><button class="primary" id="new-document">＋ מסמך</button></div><section class="panel card">${catalog.map(c=>`<div class="catalog-item"><div><strong>${esc(c.name)}</strong><small>${esc(c.description)} ${c.active?'':'· לא פעיל'}</small></div><button data-edit-document="${esc(c.document_id)}">עריכה</button></div>`).join('')}</section>`;
 const editDocument=(c={})=>{dialog(c.document_id?'עריכת מסמך':'מסמך חדש',`<form id="document-form">${field('name','שם המסמך','text',c.name||'',true)}${field('description','הנחיות ללקוח','text',c.description||'')}<label>פעיל בספרייה<select name="active"><option value="true" ${c.active!==0?'selected':''}>כן</option><option value="false" ${c.active===0?'selected':''}>לא</option></select></label><button class="primary">שמירה</button></form>`);bindForm('#document-form',async b=>{await call('/api/catalog',{...b,active:b.active==='true',document_id:c.document_id});$('#modal').close();await load();});};
 $('#back').onclick=()=>{view='templates';render();};
 $('#new-document').onclick=()=>editDocument();document.querySelectorAll('[data-edit-document]').forEach(b=>b.onclick=()=>editDocument(catalog.find(c=>c.document_id===b.dataset.editDocument)));}

function renderTemplates(){app.innerHTML=`<div class="page-heading"><div><span class="eyebrow">הגדרות המשרד</span><h1>תבניות</h1><p>לכל סוג תיק רשימת מסמכים מוכנה. מוסיפים מסמכים בתוך התבנית. שינוי בתבנית חל על תיקים חדשים בלבד.</p></div><div class="actions"><button id="library">ספריית המסמכים</button><button class="primary" id="new-template">＋ תבנית</button></div></div>${templates.map(t=>`<section class="panel card"><div class="card-head"><h2>${esc(t.name)}</h2><button data-edit-template="${esc(t.template_id)}">עריכה</button></div><ul class="file-list">${t.items.map(i=>`<li><div><strong>${esc(i.name)}</strong><small>${i.required?'חובה':'רשות'}${i.max_files>1?' · עד '+i.max_files+' קבצים':''}</small></div></li>`).join('')}</ul></section>`).join('')||'<section class="panel card"><p class="muted">עדיין אין תבניות.</p></section>'}`;
 const editTemplate=(t={})=>{dialog(t.template_id?'עריכת תבנית':'תבנית חדשה',`<form id="template-form">${field('name','שם התבנית','text',t.name||'',true)}<h3>מסמכים בתבנית</h3>${rowsEditor(t.items||[])}<button class="primary">שמירת תבנית</button></form>`);bindRows();bindForm('#template-form',async b=>{const items=selectedItems();if(!items.length)throw new Error('יש להוסיף לפחות מסמך אחד לתבנית.');await call('/api/templates',{...b,template_id:t.template_id,items});$('#modal').close();await load();});};
 $('#library').onclick=()=>{view='documents';render();};
 $('#new-template').onclick=()=>editTemplate();document.querySelectorAll('[data-edit-template]').forEach(b=>b.onclick=()=>editTemplate(templates.find(t=>t.template_id===b.dataset.editTemplate)));}

function renderSettings(){const s=settings;app.innerHTML=`<div class="page-heading"><div><span class="eyebrow">הגדרות המשרד</span><h1>הגדרות</h1><p>הפרטים שמופיעים ללקוחות ובתזכורות.</p></div></div><div class="detail-grid"><section class="panel card"><form id="settings-form"><h2>פרטי המשרד</h2><div class="form-grid">${field('office_name','שם המשרד','text',s.office_name||'',true)}${field('manager_name','מנהל/ת המשרד','text',s.manager_name||'')}${field('phone','טלפון','tel',s.phone||'')}${field('email','דוא״ל','email',s.email||'')}${field('address','כתובת','text',s.address||'')}</div><h2>התרעות על תאריך יעד</h2><div class="form-grid">${field('warning_days','התרעה צהובה, ימים לפני היעד','number',s.warning_days??7,true)}${field('urgent_days','התרעה אדומה, ימים לפני היעד','number',s.urgent_days??2,true)}</div><h2>נוסח תזכורת בוואטסאפ</h2><label class="wide">נוסח ההודעה<textarea name="whatsapp_template" rows="7" maxlength="1000" placeholder="ריק = הנוסח הרגיל">${esc(s.whatsapp_template||'')}</textarea></label><p class="muted">אפשר לשלב: {client} שם הלקוח, {case} שם התיק, {period} תקופה, {due} תאריך יעד, {missing} רשימת המסמכים החסרים, {link} הקישור האישי, {office} שם המשרד.</p><button class="primary">שמירת ההגדרות</button></form></section>
<aside><section class="panel card"><h3>לוגו המשרד</h3><div id="logo-preview"></div><label>קובץ לוגו<input type="file" id="logo-file" accept=".png,.jpg,.jpeg,image/png,image/jpeg"></label><p class="muted">PNG או JPG, עד 200KB. הלוגו נשמר מיד ולא משנה את הטופס.</p><div class="actions"><button type="button" class="primary" id="logo-upload">העלאת לוגו</button><button type="button" id="logo-remove">הסרת הלוגו</button></div></section><section class="panel card"><h3>ייצוא נתונים</h3><p class="muted">קובץ CSV שנפתח באקסל, לגיבוי או להעברה לתוכנת הנהלת חשבונות.</p><div class="actions"><button type="button" data-export="clients">ייצוא לקוחות</button><button type="button" data-export="cases">ייצוא תיקים</button></div></section></aside></div>`;
 // Logo changes only redraw the preview, so unsaved form fields stay as typed.
 const preview=()=>{$('#logo-preview').innerHTML=settings.logo_version?`<img src="${esc(window.PORTAL_CONFIG.api)}/api/logo?v=${Number(settings.logo_version)}" alt="לוגו המשרד">`:'<p class="muted">עדיין לא הועלה לוגו.</p>';$('#logo-remove').hidden=!settings.logo_version;};preview();
 bindForm('#settings-form',async b=>{settings=await call('/api/settings',{...b,warning_days:Number(b.warning_days),urgent_days:Number(b.urgent_days)});applyBranding(settings);toast('ההגדרות נשמרו');view='cases';await load();});
 const logo=async data=>{const fresh=await call('/api/settings/logo',{data});settings={...settings,logo_version:fresh.logo_version};applyBranding(fresh);preview();};
 $('#logo-upload').onclick=async()=>{const f=$('#logo-file').files[0];if(!f){toast('יש לבחור קובץ לוגו.');return;}if(f.size>200*1024){toast('קובץ הלוגו גדול מ־200KB.');return;}try{await logo(await new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=fail;r.readAsDataURL(f);}));$('#logo-file').value='';toast('הלוגו עודכן');}catch(e){toast(e.message);}};
 $('#logo-remove').onclick=async()=>{try{await logo('');toast('הלוגו הוסר');}catch(e){toast(e.message);}};
 document.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{try{const r=await call('/api/csv/export',{entity:b.dataset.export}),url=URL.createObjectURL(new Blob([r.csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=b.dataset.export+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message);}});}

$('#logout').onclick=async()=>{try{await call('/api/logout',{});}finally{token='';sessionStorage.removeItem('office_session');$('#logout').hidden=true;login();}};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(!token)return;view=b.dataset.view;render();});
api('/api/branding').then(applyBranding).catch(()=>{});
if(token)load().catch(()=>{token='';sessionStorage.removeItem('office_session');login();});else login();
