-- Additive only. Case types (תבניות) an accounting office starts from, the client's "I don't have this document" answer,
-- and inquiries from the public landing page. Existing templates and documents are left as they are.
-- Documents are matched by name, so a name the office already has is reused instead of duplicated.
ALTER TABLE requirements ADD COLUMN unavailable_note TEXT;
ALTER TABLE requirements ADD COLUMN unavailable_at TEXT;
CREATE TABLE inquiries (
 inquiry_id TEXT PRIMARY KEY, name TEXT NOT NULL, contact_name TEXT NOT NULL DEFAULT '', business_number TEXT NOT NULL DEFAULT '',
 phone TEXT NOT NULL, email TEXT NOT NULL, need TEXT NOT NULL, template_id TEXT, note TEXT NOT NULL DEFAULT '', source TEXT NOT NULL DEFAULT '',
 status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','handled','dismissed')), client_id TEXT REFERENCES clients(client_id),
 created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), handled_at TEXT, handled_by TEXT REFERENCES staff(staff_id)
);
CREATE INDEX inquiries_status ON inquiries(status,created_at);
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-1','צילום ת״ז וספח');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-2','טופס 106 מכל מעסיק');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-3','אישורים שנתיים מהבנקים ובתי ההשקעות (טופס 867)');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-4','אישורי הפקדה לפנסיה ולביטוח חיים');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-5','קבלות על תרומות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-6','חוזי שכירות ואישורי הכנסה משכר דירה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-7','אישורים שנתיים מביטוח לאומי');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-8','אישורים לנקודות זיכוי (תואר, ילד עם צרכים מיוחדים)');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-9','השומה האחרונה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-10','טופסי 106 לכל השנים');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-11','אישור ניהול חשבון בנק');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-12','אישור זכאות לתואר אקדמי');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-13','אישורי ביטוח חיים פרטי');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-14','אישור ניהול חשבון או צ׳ק מבוטל');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-15','ייפוי כוח חתום לייצוג');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-16','חוזה שכירות של מקום העסק');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-17','רישיון או תעודה מקצועית');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-18','תדפיס בנק');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-19','פירוט כרטיסי אשראי');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-20','חשבוניות הכנסה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-21','מסמכי הוצאות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-22','אישורי הפקדה לפנסיה ולקרן השתלמות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-23','אישור מקדמות לביטוח לאומי');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-24','אישורי ניכוי במקור מלקוחות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-25','ספירת מלאי לסוף השנה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-26','רכישות ומכירות של רכוש קבוע');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-27','הסכמי רכב וליסינג');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-28','אישור יתרות שנתי');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-29','דוחות שכר שנתיים (טופס 126)');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-30','לוחות סילוקין להלוואות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-31','חוזים מהותיים');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-32','פרוטוקולים (למשל חלוקת דיבידנד)');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-33','אישורי יתרה מלקוחות ומספקים');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-34','תעודת התאגדות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-35','תקנון החברה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-36','ת״ז של בעלי המניות והדירקטורים');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-37','דוחות כספיים אחרונים מרואה החשבון הקודם');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-38','השומות האחרונות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-39','אישור מורשי חתימה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-40','ת״ז של בני הזוג וספח');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-41','אישורי יתרות בנק לתאריך ההצהרה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-42','אישורי יתרות בקופות גמל ובקרנות השתלמות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-43','אישורי יתרות בתיקי השקעות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-44','נסח טאבו או חוזי רכישת נדל״ן');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-45','רישיונות רכב');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-46','משכנתא והלוואות – אישורי יתרה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-47','הלוואות מבני משפחה או אליהם');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-48','הצהרת ההון הקודמת');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-49','קבלות');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-50','טופס 101 חתום');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-51','פרטי קרן הפנסיה');
INSERT OR IGNORE INTO document_catalog(document_id,name) VALUES ('ct-doc-52','אישור תיאום מס');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-annual-individual','דוח שנתי – יחיד');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,1,2,0 FROM document_catalog WHERE name='צילום ת״ז וספח' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,1,5,1 FROM document_catalog WHERE name='טופס 106 מכל מעסיק' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,1,5,2 FROM document_catalog WHERE name='אישורים שנתיים מהבנקים ובתי ההשקעות (טופס 867)' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,0,5,3 FROM document_catalog WHERE name='אישורי הפקדה לפנסיה ולביטוח חיים' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,0,10,4 FROM document_catalog WHERE name='קבלות על תרומות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,0,5,5 FROM document_catalog WHERE name='חוזי שכירות ואישורי הכנסה משכר דירה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,0,3,6 FROM document_catalog WHERE name='אישורים שנתיים מביטוח לאומי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,0,5,7 FROM document_catalog WHERE name='אישורים לנקודות זיכוי (תואר, ילד עם צרכים מיוחדים)' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-individual',document_id,0,1,8 FROM document_catalog WHERE name='השומה האחרונה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-individual');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-refund','החזר מס – שכיר');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-refund',document_id,1,2,0 FROM document_catalog WHERE name='צילום ת״ז וספח' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-refund');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-refund',document_id,1,12,1 FROM document_catalog WHERE name='טופסי 106 לכל השנים' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-refund');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-refund',document_id,1,1,2 FROM document_catalog WHERE name='אישור ניהול חשבון בנק' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-refund');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-refund',document_id,0,5,3 FROM document_catalog WHERE name='אישורים שנתיים מהבנקים ובתי ההשקעות (טופס 867)' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-refund');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-refund',document_id,0,10,4 FROM document_catalog WHERE name='קבלות על תרומות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-refund');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-refund',document_id,0,2,5 FROM document_catalog WHERE name='אישור זכאות לתואר אקדמי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-refund');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-refund',document_id,0,3,6 FROM document_catalog WHERE name='אישורי ביטוח חיים פרטי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-refund');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-refund',document_id,0,3,7 FROM document_catalog WHERE name='אישורים שנתיים מביטוח לאומי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-refund');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-open-business','פתיחת תיק – עוסק פטור או מורשה');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-open-business',document_id,1,2,0 FROM document_catalog WHERE name='צילום ת״ז וספח' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-open-business');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-open-business',document_id,1,1,1 FROM document_catalog WHERE name='אישור ניהול חשבון או צ׳ק מבוטל' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-open-business');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-open-business',document_id,1,1,2 FROM document_catalog WHERE name='ייפוי כוח חתום לייצוג' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-open-business');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-open-business',document_id,0,1,3 FROM document_catalog WHERE name='חוזה שכירות של מקום העסק' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-open-business');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-open-business',document_id,0,2,4 FROM document_catalog WHERE name='רישיון או תעודה מקצועית' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-open-business');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-annual-selfemployed','דוח שנתי – עצמאי');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,1,12,0 FROM document_catalog WHERE name='תדפיס בנק' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,1,12,1 FROM document_catalog WHERE name='פירוט כרטיסי אשראי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,1,20,2 FROM document_catalog WHERE name='חשבוניות הכנסה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,1,20,3 FROM document_catalog WHERE name='מסמכי הוצאות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,0,5,4 FROM document_catalog WHERE name='אישורי הפקדה לפנסיה ולקרן השתלמות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,0,2,5 FROM document_catalog WHERE name='אישור מקדמות לביטוח לאומי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,0,10,6 FROM document_catalog WHERE name='אישורי ניכוי במקור מלקוחות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,0,2,7 FROM document_catalog WHERE name='ספירת מלאי לסוף השנה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,0,5,8 FROM document_catalog WHERE name='רכישות ומכירות של רכוש קבוע' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,0,3,9 FROM document_catalog WHERE name='הסכמי רכב וליסינג' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-selfemployed',document_id,0,5,10 FROM document_catalog WHERE name='טופס 106 מכל מעסיק' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-selfemployed');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-annual-company','דוח שנתי – חברה בע״מ');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,1,20,0 FROM document_catalog WHERE name='תדפיס בנק' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,1,5,1 FROM document_catalog WHERE name='אישור יתרות שנתי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,1,12,2 FROM document_catalog WHERE name='פירוט כרטיסי אשראי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,1,3,3 FROM document_catalog WHERE name='דוחות שכר שנתיים (טופס 126)' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,0,2,4 FROM document_catalog WHERE name='ספירת מלאי לסוף השנה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,0,5,5 FROM document_catalog WHERE name='רכישות ומכירות של רכוש קבוע' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,0,5,6 FROM document_catalog WHERE name='לוחות סילוקין להלוואות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,0,10,7 FROM document_catalog WHERE name='חוזים מהותיים' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,0,5,8 FROM document_catalog WHERE name='פרוטוקולים (למשל חלוקת דיבידנד)' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,0,10,9 FROM document_catalog WHERE name='אישורי יתרה מלקוחות ומספקים' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-annual-company',document_id,0,10,10 FROM document_catalog WHERE name='אישורי ניכוי במקור מלקוחות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-annual-company');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-new-company','קליטת חברה חדשה');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-company',document_id,1,1,0 FROM document_catalog WHERE name='תעודת התאגדות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-company',document_id,1,1,1 FROM document_catalog WHERE name='תקנון החברה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-company',document_id,1,10,2 FROM document_catalog WHERE name='ת״ז של בעלי המניות והדירקטורים' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-company',document_id,1,1,3 FROM document_catalog WHERE name='אישור ניהול חשבון או צ׳ק מבוטל' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-company',document_id,0,3,4 FROM document_catalog WHERE name='דוחות כספיים אחרונים מרואה החשבון הקודם' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-company',document_id,0,3,5 FROM document_catalog WHERE name='השומות האחרונות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-company',document_id,0,1,6 FROM document_catalog WHERE name='אישור מורשי חתימה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-company');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-company',document_id,0,1,7 FROM document_catalog WHERE name='ייפוי כוח חתום לייצוג' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-company');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-capital-declaration','הצהרת הון');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,1,4,0 FROM document_catalog WHERE name='ת״ז של בני הזוג וספח' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,1,10,1 FROM document_catalog WHERE name='אישורי יתרות בנק לתאריך ההצהרה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,1,10,2 FROM document_catalog WHERE name='אישורי יתרות בקופות גמל ובקרנות השתלמות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,0,10,3 FROM document_catalog WHERE name='אישורי יתרות בתיקי השקעות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,0,5,4 FROM document_catalog WHERE name='נסח טאבו או חוזי רכישת נדל״ן' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,0,4,5 FROM document_catalog WHERE name='רישיונות רכב' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,0,5,6 FROM document_catalog WHERE name='משכנתא והלוואות – אישורי יתרה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,0,5,7 FROM document_catalog WHERE name='הלוואות מבני משפחה או אליהם' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-capital-declaration',document_id,0,1,8 FROM document_catalog WHERE name='הצהרת ההון הקודמת' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-capital-declaration');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-vat-period','דיווח תקופתי למע״מ');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-vat-period',document_id,1,20,0 FROM document_catalog WHERE name='חשבוניות הכנסה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-vat-period');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-vat-period',document_id,1,20,1 FROM document_catalog WHERE name='מסמכי הוצאות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-vat-period');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-vat-period',document_id,0,3,2 FROM document_catalog WHERE name='תדפיס בנק' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-vat-period');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-vat-period',document_id,0,3,3 FROM document_catalog WHERE name='פירוט כרטיסי אשראי' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-vat-period');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-vat-period',document_id,0,20,4 FROM document_catalog WHERE name='קבלות' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-vat-period');
INSERT OR IGNORE INTO templates(template_id,name) VALUES ('ct-new-employee','קליטת עובד חדש');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-employee',document_id,1,1,0 FROM document_catalog WHERE name='טופס 101 חתום' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-employee');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-employee',document_id,1,2,1 FROM document_catalog WHERE name='צילום ת״ז וספח' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-employee');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-employee',document_id,1,1,2 FROM document_catalog WHERE name='אישור ניהול חשבון או צ׳ק מבוטל' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-employee');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-employee',document_id,0,2,3 FROM document_catalog WHERE name='פרטי קרן הפנסיה' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-employee');
INSERT OR IGNORE INTO template_items(template_id,document_id,required,max_files,position) SELECT 'ct-new-employee',document_id,0,1,4 FROM document_catalog WHERE name='אישור תיאום מס' AND EXISTS(SELECT 1 FROM templates WHERE template_id='ct-new-employee');
